create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  lemon_squeezy_subscription_id text unique,
  lemon_squeezy_customer_id text,
  lemon_squeezy_order_id text,
  lemon_squeezy_product_id text,
  lemon_squeezy_variant_id text,
  status text not null default 'inactive',
  status_formatted text,
  plan_name text,
  customer_email text,
  renews_at timestamptz,
  ends_at timestamptz,
  trial_ends_at timestamptz,
  update_payment_method_url text,
  customer_portal_url text,
  raw_event jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists subscriptions_user_id_key on public.subscriptions (user_id);
create index if not exists subscriptions_status_idx on public.subscriptions (status);
create index if not exists subscriptions_subscription_id_idx on public.subscriptions (lemon_squeezy_subscription_id);

alter table public.subscriptions enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'subscriptions'
      and policyname = 'Users can view their own subscription'
  ) then
    create policy "Users can view their own subscription"
      on public.subscriptions
      for select
      using (auth.uid() = user_id);
  end if;
end
$$;